# Generated by Django 5.2.1 on 2025-05-15 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_attendees_count_event_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(default="12:00", verbose_name="time"),
            preserve_default=False,
        ),
    ]
