# Generated by Django 5.2.1 on 2025-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_date_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, default=1, max_digits=10, verbose_name="latitude"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default=1, max_length=255, verbose_name="location"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8, default=1, max_digits=10, verbose_name="longitude"
            ),
            preserve_default=False,
        ),
    ]
