# Generated by Django 5.2.1 on 2025-05-15 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_attendees_count_event_is_active"),
        ("type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="price")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("cancelled", "ملغي"),
                            ("completed", "مكتمل"),
                        ],
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "نقدي"), ("card", "بطاقة")],
                        max_length=255,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("paid", "مدفوع"),
                            ("failed", "فشل"),
                            ("waiting_for_refund", "قيد الانتظار للاسترجاع"),
                            ("refunded", "مسترجع"),
                            ("cancelled", "ملغي"),
                        ],
                        max_length=255,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "charge_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="charge id"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="events.event",
                    ),
                ),
                (
                    "related_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="type.type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "unique_together": {("user", "event", "date")},
            },
        ),
    ]
