# Generated by Django 5.2.1 on 2025-05-15 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_date_event_time"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("user", "event")},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
    ]
