# Generated by Django 5.2.1 on 2025-05-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="related_type",
        ),
    ]
