# Generated by Django 4.2.15 on 2025-03-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for the field (e.g., 'Name')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "english",
                    models.CharField(help_text="English translation", max_length=255),
                ),
                (
                    "arabic",
                    models.CharField(help_text="Arabic translation", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
            },
        ),
    ]
