# Generated by Django 4.2.15 on 2025-03-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Translation",
        ),
    ]
